if(NOT PISTACHE_FOUND)
	if(NOT PISTACHE_ROOT_DIR)
		set(PISTACHE_ROOT_DIR ${CMAKE_INSTALL_PREFIX})
	endif(NOT PISTACHE_ROOT_DIR)

	# find_path
	include(FindPackageHandleStandardArgs)
	find_package_handle_standard_args(PISTACHE 
		FOUND_VAR PISTACHE_FOUND
		REQUIRED_VARS PISTACHE_LIBRARY PISTACHE_INCLUDE_DIR
		VERSION_VAR)

endif(NOT PISTACHE_FOUND)
